import "./globals.css";
import NextTopLoader from "nextjs-toploader";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import LayoutPage from "@/components/page/LayoutPage";
const inter = Inter({ subsets: ["latin"] });
import "yakuhanjp";
import { getRandomBangDreamBandMember } from "@/lib/BangDreamApiHandler";
import dynamic from "next/dynamic";

export const metadata: Metadata = {
  title: "Bang Dream",
  description: "Generated by create next app",
};
export const revalidate = 10;
const LayoutPage = dynamic(() => import("@/components/page/LayoutPage"), {
  ssr: false,
});
export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const randomBangDreamBandMemberDatas = await getRandomBangDreamBandMember();
  const [randomBangDreamBandMembers] = await Promise.all([
    randomBangDreamBandMemberDatas,
  ]);
  if (!randomBangDreamBandMemberDatas) {
    return [];
  }

  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="dist/css/yakuhanjp.min.css" />
      </head>
      <body className="overflow-x-hidden scrollbar-thin scrollbar-thumb-[#7f7f7f] ">
        <NextTopLoader color="#b92b5d" />
        <LayoutPage randomBangDreamBandMembers={randomBangDreamBandMembers}>
          {children}
        </LayoutPage>
      </body>
    </html>
  );
}
